// <auto-generated />
using IntegrationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntegrationService.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntegrationService.Data.Entities.MessageFormat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scheme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MessageFormats");

                    b.HasData(
                        new
                        {
                            Id = 1000L,
                            Name = "Upackage",
                            Scheme = "{\r\n	\"definitions\": {},\r\n	\"$schema\": \"http://json-schema.org/draft-07/schema#\", \r\n	\"$id\": \"https://example.com/object1636286636.json\", \r\n	\"title\": \"Upackage format\", \r\n	\"type\": \"object\",\r\n	\"required\": [\r\n		\"integrationId\",\r\n		\"content\"\r\n	],\r\n	\"properties\": {\r\n		\"integrationId\": {\r\n			\"$id\": \"#root/integrationId\", \r\n			\"title\": \"Integrationid\", \r\n			\"type\": \"string\",\r\n			\"default\": \"\",\r\n			\"examples\": [\r\n				\"26b13510-d202-4734-bb12-10433a950f35\"\r\n			]\r\n		},\r\n		\"content\": {\r\n			\"$id\": \"#root/content\", \r\n			\"title\": \"Content\", \r\n			\"type\": \"string\",\r\n			\"default\": \"\",\r\n			\"examples\": [\r\n				\"@@JJKJHHU#####\"\r\n			]\r\n		}\r\n	}\r\n}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
