//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationService.Data {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationService.Data.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///	&quot;definitions&quot;: {},
        ///	&quot;$schema&quot;: &quot;http://json-schema.org/draft-07/schema#&quot;, 
        ///	&quot;$id&quot;: &quot;https://example.com/object1636286636.json&quot;, 
        ///	&quot;title&quot;: &quot;Upackage format&quot;, 
        ///	&quot;type&quot;: &quot;object&quot;,
        ///	&quot;required&quot;: [
        ///		&quot;integrationId&quot;,
        ///		&quot;content&quot;
        ///	],
        ///	&quot;properties&quot;: {
        ///		&quot;integrationId&quot;: {
        ///			&quot;$id&quot;: &quot;#root/integrationId&quot;, 
        ///			&quot;title&quot;: &quot;Integrationid&quot;, 
        ///			&quot;type&quot;: &quot;string&quot;,
        ///			&quot;default&quot;: &quot;&quot;,
        ///			&quot;examples&quot;: [
        ///				&quot;26b13510-d202-4734-bb12-10433a950f35&quot;
        ///			]
        ///		},
        ///		&quot;content&quot;: {
        ///			&quot;$id&quot;: &quot;#root/content&quot;, 
        ///			&quot;t [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PredefinedFormatUpackage {
            get {
                return ResourceManager.GetString("PredefinedFormatUpackage", resourceCulture);
            }
        }
    }
}
